In [1]:
import numpy as np

#### `Membuat Array`
Salah satu cara kita dapat menginisialisasi array NumPy adalah dari nested Python lists


In [2]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

Kita dapat mengakses elemen dalam array menggunakan tanda kurung siku. Saat kalian mengakses elemen, ingatlah bahwa peng __indeks__ an di NumPy dimulai dari 0. Artinya, jika ingin mengakses elemen pertama dalam array, kita akses elemen "0".

In [3]:
print(a[0])  # Output: [1 2 3 4]

[1 2 3 4]


### `Indexing Array`

#### 1. `Mengindeks dengan Tuple Bilangan Bulat Non-Negatif`

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1, 2])  # Output: 6

6


#### 2. `Mengindeks dengan Boolean` 

In [5]:
arr = np.array([1, 2, 3, 4, 5])
mask = np.array([True, False, True, False, True])
print(arr[mask])  # Output: [1, 3, 5]

[1 3 5]


#### `3.Mengindeks dengan Array Lain` 

In [6]:
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([1, 3, 4])
print(arr[indices])  # Output: [20, 40, 50]

[20 40 50]


#### `4.Mengindeks dengan Bilangan Bulat`

In [7]:
arr = np.array([5, 10, 15, 20])
print(arr[2])  # Output: 15

15


### `Rank dan Shape Array`

`Rank dari Array (Rank adalah jumlah dimensi dari array)`

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)  # Output: 2 (karena array memiliki 2 dimensi)

2


`Shape dari Array (Shape adalah tuple bilangan bulat yang menunjukkan ukuran array di setiap dimensi)`

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # Output: (2, 3) (artinya array memiliki 2 baris dan 3 kolom)

(2, 3)


### `Creating Array`
Ada beberapa cara membuat Array 
- `np.array()`
- `np.zeros()`
- `np.ones()`
- `np.empty()`
- n`p.arange()`


`np.array()` Membuat array dari daftar atau tuple.

In [10]:
arr = np.array([1, 2, 3])
print(arr)  # Output: [1 2 3]


[1 2 3]


`np.zeros()` Membuat array dengan semua elemen nol.

In [11]:
arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


`np.ones()` Membuat array dengan semua elemen satu.

In [12]:
arr = np.ones((2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


`Membuat array tanpa menginisialisasi nilainya (nilai acak)`

In [13]:
arr = np.empty((2, 3))
print(arr)  # Output: # [[1. 1. 1.]#  [1. 1. 1.]]

[[1. 1. 1.]
 [1. 1. 1.]]


`np.arange` Membuat array dengan nilai berurutan.

In [14]:
arr = np.arange(1, 10, 2)
print(arr)  # Output: [1 3 5 7 9]

[1 3 5 7 9]


Apa yang dilakukan arange([start], stop, [step]) adalah menghasilkan deretan angka dari awal hingga sebelum angka berhenti dengan langkah tertentu. Ini adalah arti dari np.arange(0, 10, 2)

NumPy membuat array mulai dari 0 hingga 10 (tidak termasuk 10) dengan kenaikan 2 setiap langkah.

Hal penting yang perlu diingat adalah bahwa angka berhenti (10) tidak akan dimasukkan dalam array. Contoh lain:np.arange(2, 29, 5)# Output: array([ 2,  7, 12, 17, 22, 27])

In [15]:
np.arange(2, 29, 5)  # Output: array([ 2,  7, 12, 17, 22, 27])

array([ 2,  7, 12, 17, 22, 27])

### `Add, Remove, and Sort`
- `np.append()`
- `np.delete()`
- `np.sort()`

#### `np.append()`

In [16]:
arr = np.array([1, 2, 3])
new_arr = np.append(arr, [4, 5])
print(new_arr)  # Output: [1 2 3 4 5]

[1 2 3 4 5]


#### `np.delete()` 

In [17]:
arr = np.array([1, 2, 3, 4, 5])
new_arr = np.delete(arr, [1, 3])
print(new_arr)  # Output: [1 3 5]

[1 3 5]


#### `np.sort()`

In [18]:
arr = np.array([3, 1, 2, 5, 4])
sorted_arr = np.sort(arr)
print(sorted_arr) # Output: [1 2 3 4 5]

[1 2 3 4 5]


### `Shape dan Size` 
- `ndarray.ndim()`
- `ndarray.size()`
- `ndarray.shape()`


`ndarray.ndim()` Mengembalikan jumlah dimensi (rank) dari array.

In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)  # Output: 2

2


`ndarray.size()` Mengembalikan jumlah total elemen dalam array.

In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.size)  # Output: 6

6


`ndarray.shape()` Mengembalikan bentuk array sebagai tuple yang menunjukkan ukuran di setiap dimensi.

In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # Output: (2, 3)


(2, 3)


### `Reshape`
- `np.reshape()` 
Fungsi ini digunakan untuk mengubah bentuk (shape) dari array tanpa mengubah data di dalamnya. Fungsi ini mengembalikan array baru dengan bentuk yang diinginkan. Cara pakainya seperti berikut:
  - `np.reshape(a, newshape)`
  
  a adalah Array yang ingin diubah bentuknya.
  
  newshape adalah Tuple yang menentukan bentuk baru. Jumlah elemen dalam array asli harus sesuai dengan jumlah elemen dalam bentuk baru.


Membuat array 1D dengan 6 elemen

In [22]:
arr = np.array([1, 2, 3, 4, 5, 6])


Mengubah bentuk array menjadi 2D (2 baris dan 3 kolom)

In [23]:
reshaped_arr = np.reshape(arr, (2, 3))
print(reshaped_arr)  # Output:# [[1 2 3]#  [4 5 6]]

[[1 2 3]
 [4 5 6]]


Mengubah bentuk array menjadi 3D (2 blok, 1 baris, dan 3 kolom)

In [24]:
reshaped_arr_3d = np.reshape(arr, (2, 1, 3))
print(reshaped_arr_3d) # Output:# [[[1 2 3]]#  [[4 5 6]]]

[[[1 2 3]]

 [[4 5 6]]]


### `Convert 1D menjadi 2D`

In [25]:
np.newaxis()

TypeError: 'NoneType' object is not callable

digunakan untuk menambahkan dimensi baru ke array, meningkatkan rank array. Ini sering digunakan untuk mengubah array 1D menjadi 2D dengan menambahkan dimensi baru.

`Array 1D` 

In [ ]:
arr = np.array([1, 2, 3])
# Output:# [[1 2 3]]

`Ubah menjadi 2D`

In [27]:
arr_2d = arr[:, np.newaxis]
print(arr_2d)# Output:# [[1]#  [2]#  [3]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


`Atau menambah dimensi baru di axis lainnya`

In [28]:
arr_2d_alt = arr[np.newaxis, :]
print(arr_2d_alt)

[[1 2 3 4 5 6]]


### `Indexing dan Slicing`
Kita bisa mengindeks dan slice array NumPy dengan cara yang sama seperti pada list Python.


In [26]:
data = np.array([1, 2, 3])
# Menampilkan seluruh array
print(data)  # Output: [1 2 3]
# Indexing: Mengakses elemen pertama

print(data[0])  # Output: 1# 
# Indexing: Mengakses elemen kedua

print(data[1])  # Output: 2# 
# Slicing: Mengambil elemen dari indeks 0 sampai 2 (tidak termasuk 2)

print(data[0:2])  # Output: [1 2]# 
# Slicing: Mengambil elemen dari indeks 1 sampai akhir

print(data[1:])  # Output: [2 3]# 
# Slicing: Mengambil dua elemen terakhir

print(data[-2:])  # Output: [2 3]

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


### `Indexing dan Slicing dengan Kondisi`
Kalian mungkin ingin mengambil bagian dari array atau elemen array tertentu untuk digunakan dalam analisis lebih lanjut atau operasi tambahan. Untuk melakukannya, kalian perlu membuat subset, memotong (slicing), dan/atau mengindeks array kalian.

Jika kalian ingin memilih nilai dari array yang memenuhi kondisi tertentu, ini dapat dilakukan langsung dengan NumPy.

In [33]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
print(a[a >= 5])

[ 5  6  7  8  9 10 11 12]


Kalian juga dapat memilih angka yang sama dengan atau lebih besar dari 5, dan menggunakan kondisi tersebut untuk mengindeks array.

In [36]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [37]:
print(a[a >= 5])

[ 5  6  7  8  9 10 11 12]


Kalian juga dapat memilih elemen yang habis dibagi 2

In [38]:
# Memilih elemen yang habis dibagi 2
divisible_by_2 = a[a % 2 == 0]
print(divisible_by_2) # Output: [ 2  4  6  8 10 12]

[ 2  4  6  8 10 12]


### `Membuat Array dari Data yang Ada`
Kalian dapat dengan mudah membuat array baru dari bagian array yang sudah ada dengan slicing dan indexing. Misalnya, dengan array berikut

In [39]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])