In [107]:
import numpy as np

In [108]:
# python_list 
a = [1,2,3]
b = [4,5,6]

print(a+b)

[1, 2, 3, 4, 5, 6]


#### `List General`

In [109]:
c= [0,0,0]
for i in range(len(c)):
  c[i] = a[i]+b[i]
print(c)

[5, 7, 9]


#### `Numpy vector mult`

In [110]:
# python_list
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a+b)

[5 7 9]


In [111]:
# def add(a,b):
#   c[0] = 
#   for i in range(len(a)):
#   c[i] = a[i] + b[i]

#   return c

In [112]:
a = range(10000)
b = range(10000)

np_a = np.array(a)
np_b = np.array(b)

In [113]:
# %timeit add(a,b):

In [114]:
%timeit np_a + np_b

5.3 µs ± 446 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# `Vector Arithmetic`

In [115]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a+b)
print(a-b)

print(a+b)
print(a/b)


# dot product 
print(a @ b)
print(np.dot(a,b))
print(a.dot(b))

# cross product
print(np.cross(a,b)) 

[5 7 9]
[-3 -3 -3]
[5 7 9]
[0.25 0.4  0.5 ]
32
32
32
[-3  6 -3]


In [116]:
c = 3

print(a+c)
print(a-c)

print(a+c)
print(a/c)

[4 5 6]
[-2 -1  0]
[4 5 6]
[0.33333333 0.66666667 1.        ]


# `Vector Norm`

In [117]:
print(np.linalg.norm(a))

# Euclidean Distance -> Nearest distance
print(np.sqrt(1**2 +  2**2 + 3**2 ))

#Manhattan Distance 
print(np.linalg.norm(a, ord=1))

3.7416573867739413
3.7416573867739413
6.0


# `Matrix`

a = np.array([      -> colomn
            [baris]
])

In [118]:
A = np.array([[1, 2], [4, 5]])
B = np.array([[7,8], [10,11] ])
print(A.shape)
print(B.shape)

(2, 2)
(2, 2)


In [119]:
print(A @ B)

[[27 30]
 [78 87]]


In [120]:
tugas = np.random.normal(70,10,50)
pract = np.random.normal(80, 5, 50)
uts = np.random.normal(70, 5, 50)
uas = np.random.normal(70, 10, 50)

mhs = np.arange(1,51)

In [121]:
res = 0.2 * tugas + 0.2 * pract + 0.3 * uts + 0.3 * uas
res

array([73.57706301, 69.92214603, 76.23990766, 70.326128  , 76.62776886,
       76.75925826, 72.5917389 , 83.70775489, 75.59103869, 78.17914062,
       72.97694626, 74.18291962, 73.00725965, 71.43095074, 74.52909271,
       68.52999448, 66.95294877, 64.71843571, 69.25396406, 73.52721397,
       62.01326804, 79.70345701, 78.33243335, 71.62453326, 74.52261133,
       69.82015871, 70.22697465, 71.6582779 , 67.10273139, 77.52308334,
       68.0795441 , 68.56580278, 82.39046341, 70.52118027, 67.43685535,
       69.55166636, 66.83959535, 71.608581  , 71.55512732, 70.34135298,
       76.04295733, 66.28272388, 75.97455024, 75.21182766, 79.83182774,
       73.42521708, 76.30919917, 68.51771667, 76.33884232, 70.79097261])

In [122]:
# not pass 
passgrade = res[res < 70]
print(passgrade.size)
print(len(passgrade))

15
15


In [123]:
mhs[res <70]

array([ 2, 16, 17, 18, 19, 21, 26, 29, 31, 32, 35, 36, 37, 42, 48])

In [124]:
res.mean()

72.61550406955526

In [125]:
passgrade.mean()

67.57250344589595

In [126]:
n_pass = (uas <= 70) & (res > 70)
n_pass = np.sum(~n_pass)
n_pass

36