## pyhton list vs numpy array

In [ ]:
# list python
a = [1, 2, 3]
b = [4, 5, 6]

print(a+b)

[1, 2, 3, 4, 5, 6]


In [ ]:
# penjumlahan vektor dengan list python
c = [0,0,0]
for i in range(len(c)):
    c[i] = a[i] + b[i]

print(c)

[5, 7, 9]


In [ ]:
def jumlah(a,b):
    c = [0] * len(a)
    for i in range(len(c)):
        c[i] = a[i] + b[i]
    return c

In [ ]:
# import numpy
import numpy as np

In [ ]:
# Mendefinisikan vektor dengan numpy
a = [1, 2, 3]
np_a = np.array(a)
b = [4, 5, 6]
np_b = np.array(b)

# penjumlahan vektor dengan numpy
print(np_a + np_b)

[5 7 9]


## Perbandingan Performa

In [ ]:
a = range(10000)
b = range(10000)

np_a = np.array(a)
np_b = np.array(b)

In [ ]:
%timeit jumlah(a,b)

1.2 ms ± 28.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [ ]:
%timeit np_a + np_b

2.73 µs ± 55.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## Array

In [ ]:
# 1D array (vector)
a = [1, 2, 3]
np_a = np.array(a)

# 2D array (matrix)
A = [[1, 2], [3, 4]]
np_A = np.array(A)

# nD array (tensor)
T = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
np_T = np.array(T)


print(np_a.shape)
print(np_A.shape)
print(np_T.shape)

(3,)
(2, 2)
(2, 2, 2)


## Operasi vektor

In [ ]:
# Operasi aritmatika vektor dengan numpy
a = [1, 2, 3]
b = [4, 5, 6]

np_a = np.array(a)
np_b = np.array(b)

# Element-wise
print('penjumlahan: ', np_a + np_b)
print('pengurangan: ', np_a - np_b)
print('perkalian: ', np_a * np_b)
print('pembagian: ', np_a / np_b)

# dot product
print('dot product: ')
print(np.dot(np_a, np_b))
print(np_a.dot(np_b))
print(np_a @ np_b)

# cross product
print('cross product: ', np.cross(np_a, np_b))

penjumlahan:  [5 7 9]
pengurangan:  [-3 -3 -3]
perkalian:  [ 4 10 18]
pembagian:  [0.25 0.4  0.5 ]
dot product: 
32
32
32
cross product:  [-3  6 -3]


In [ ]:
# operasi vektor dengan skalar
c = [1, 2, 3]
vect_c = np.array(c)

print('Addition       : ', vect_c + 2)
print('Substraction   : ', vect_c - 2)
print('Multiplication : ', vect_c * 2)
print('Division       : ', vect_c / 2)

Addition       :  [3 4 5]
Substraction   :  [-1  0  1]
Multiplication :  [2 4 6]
Division       :  [0.5 1.  1.5]


In [ ]:
# norm vektor

a = [1, 2, 3]
np_a = np.array(a)

print('euclidean norm vektor a: ', np.linalg.norm(np_a))
# manhattan norm
print('manhattan norm vektor a: ', np.linalg.norm(np_a, ord=1))

euclidean norm vektor a:  3.7416573867739413
manhattan norm vektor a:  6.0


## Matrix

In [ ]:
# Define a matrix
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

matrix_A = np.array(A)
matrix_A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Check type of the variable and matrix size

print('Type : ', type(matrix_A))
print('Size : ', matrix_A.shape)

Type :  <class 'numpy.ndarray'>
Size :  (3, 3)


## Operasi Matrix

In [ ]:
# Arithmetic operations with a scalar (addition, substraction, multiplication, and division)

B = [[1, 2],
     [3, 4],
     [5, 6]]

matrix_B = np.array(B)

print('Addition       : \n', matrix_B + 2)
print('')

print('Substraction   : \n', matrix_B - 2)
print('')

print('Multiplication : \n', matrix_B * 2)
print('')

print('Division       : \n', matrix_B / 2)
print('')

Addition       : 
 [[3 4]
 [5 6]
 [7 8]]

Substraction   : 
 [[-1  0]
 [ 1  2]
 [ 3  4]]

Multiplication : 
 [[ 2  4]
 [ 6  8]
 [10 12]]

Division       : 
 [[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]



In [ ]:
# Arithmetic operations between matrices (addition, substraction, multiplication, and division)

C = [[1, 2],
     [3, 4],
     [5, 6]]

matrix_C = np.array(C)

D = [[7, 8],
     [9, 10],
     [11, 12]]
matrix_D = np.array(D)

print('Addition     : \n', matrix_C + matrix_D)
print('')

print('Substraction : \n', matrix_C - matrix_D)
print('')

print('Division     : \n', matrix_C / matrix_D)
print('')

print('Multiplication (element-wise) : \n', matrix_C * matrix_D)
print('')

Addition     : 
 [[ 8 10]
 [12 14]
 [16 18]]

Substraction : 
 [[-6 -6]
 [-6 -6]
 [-6 -6]]

Division     : 
 [[0.14285714 0.25      ]
 [0.33333333 0.4       ]
 [0.45454545 0.5       ]]

Multiplication (element-wise) : 
 [[ 7 16]
 [27 40]
 [55 72]]



In [ ]:
# Multiplication (dot product) between matrices

E = [[1, 2],
     [3, 4],
     [5, 6]]

F = [[1, 2],
     [3, 4]]

matrix_E = np.array(E)
matrix_F = np.array(F)

print('Multiplication (dot product)')

print('Syntax 1 : \n', matrix_E @ matrix_F)
print('')

print('Syntax 2 : \n', matrix_E.dot(matrix_F))
print('')

print('Syntax 3 : \n', np.dot(matrix_E, matrix_F))
print('')

Multiplication (dot product)
Syntax 1 : 
 [[ 7 10]
 [15 22]
 [23 34]]

Syntax 2 : 
 [[ 7 10]
 [15 22]
 [23 34]]

Syntax 3 : 
 [[ 7 10]
 [15 22]
 [23 34]]



In [ ]:
# Multiplication between a matrix and an identity matrix

G = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

matrix_G = np.array(G)
print('Original matrix : \n', matrix_G)
print('')

matrix_I = np.eye(3, 3)
print('Identity matrix : \n', matrix_I)
print('')

print('Multiplication result : \n', matrix_G @ matrix_I)

Original matrix : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Identity matrix : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Multiplication result : 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## Tipe Matrix

In [ ]:
# Type of matrix

print('Upper triangular matrix : \n', np.triu(matrix_A))
print('')

print('Lower triangular matrix : \n', np.tril(matrix_A))
print('')

print('Diagonal matrix         : \n', np.diag(matrix_A))
print('')

print('Identity matrix (3,3)   : \n', np.eye(3, 3))
print('')

Upper triangular matrix : 
 [[1 2 3]
 [0 5 6]
 [0 0 9]]

Lower triangular matrix : 
 [[1 0 0]
 [4 5 0]
 [7 8 9]]

Diagonal matrix         : 
 [1 5 9]

Identity matrix (3,3)   : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



## Transpose & Determinant

In [ ]:
# Transpose of a matrix

H = [[1, 2],
     [3, 4],
     [5, 6]]

matrix_H = np.array(H)

print('Original matrix : \n', matrix_H)
print('')

print('Transpose matrix : \n', matrix_H.T)
print('')

Original matrix : 
 [[1 2]
 [3 4]
 [5 6]]

Transpose matrix : 
 [[1 3 5]
 [2 4 6]]



In [ ]:
# Determinant of a matrix

J = [[1, 2],
     [3, 4]]

K = [[10, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

matrix_J = np.array(J)
matrix_K = np.array(K)

print('Determinant of matrix_H : ', np.linalg.det(matrix_J))
print('Determinant of matrix_J : ', np.linalg.det(matrix_K))

Determinant of matrix_H :  -2.0000000000000004
Determinant of matrix_J :  -26.99999999999998


## Inverse

In [ ]:
# Inverse of matrix

L = [[1, 2],
     [3, 4]]

matrix_L = np.array(L)
inverse_matrix_L = np.linalg.inv(matrix_L)

print('Original matrix : \n', matrix_L)
print('')

print('Inverse matrix  : \n', inverse_matrix_L)
print('')

print('Multiplication between a matrix and its inverse : \n', matrix_L @ inverse_matrix_L)

Original matrix : 
 [[1 2]
 [3 4]]

Inverse matrix  : 
 [[-2.   1. ]
 [ 1.5 -0.5]]

Multiplication between a matrix and its inverse : 
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


## Slicing & Indexing

## Studi Kasus

In [ ]:
# dosen dgn 50 mhs
# tugas, praktikum, UTS, UAS

# nilai akhir = 10%(nilai tugas) + 15%(nilai praktikum) + 35%(nilai UTS) + 40%(nilai UAS)

nilai_tugas = np.random.normal(70, 10, 50)
nilai_praktikum = np.random.normal(80, 5, 50)
nilai_uts = np.random.normal(75, 7, 50)
nilai_uas = np.random.normal(85, 3, 50)
absen = np.array(range(1,51))

In [ ]:
absen

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])