# Python list vs Numpy array

In [ ]:
# python list vs numpy array

# python list

a = [1, 2, 3]
b = [4, 5, 6]

print(a + b)

[1, 2, 3, 4, 5, 6]


In [ ]:
c = [0,0,0]

for i in range(len(c)):
    c[i] = a[i] + b[i]

print(c)

[5, 7, 9]


In [ ]:
def add(a, b):
    c = [0] * len(a)
    for i in range(len(c)):
        c[i] = a[i] + b[i]
    return c

In [ ]:
# numpy array
import numpy as np

np_a = np.array(a)
np_b = np.array(b)

print(np_a + np_b)

[5 7 9]


## Perbandingan performa

In [ ]:
a = range(10000)
b = range(10000)

np_a = np.array(a)
np_b = np.array(b)

In [ ]:
%timeit add(a, b)

4.19 ms ± 531 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
%timeit np_a + np_b

9.44 µs ± 722 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Array

In [ ]:
print(type(np_a))

<class 'numpy.ndarray'>


In [ ]:
# define array

a = np.array([1, 2, 3])
print(a)
b = np.arange(1, 10, 2)
print(b)
c = np.zeros((3))
print(c)
d = np.ones((3))
print(d)

[1 2 3]
[1 3 5 7 9]
[0. 0. 0.]
[1. 1. 1.]


# Array Dimensions

In [ ]:
# 0 dimension array (scalar)
a = np.array(1)
print(a.shape)

# 1 dimension array (vector)
b = [1,2,3]
b = np.array(b)
print(b.shape)

# 2 Dimension array (matrix)
c = [[1, 2, 3],[4,5,6], [7,8,9]]
c = np.array(c)
print(c.shape)

# 3 or more Dimension array (tensor)
d = [[[[1, 2, 3],[4,5,6], [7,8,9]],[[1, 2, 3],[4,5,6], [7,8,9]]]]
d = np.array(d)
print(d.shape)

()
(3,)
(3, 3)
(1, 2, 3, 3)


# Vector

In [ ]:
# Operasi aritmatika

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# antar vektor (element wise)
print(a + b)
print(a - b)

print(a * b)
print(a / b)

# dot product
print(a @ b)
print(np.dot(a, b))
print(a.dot(b))

# cross product
print(np.cross(a, b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
32
32
32
[-3  6 -3]


In [ ]:
# vektor dengan skalar

c = 3
print(a)
print(a + c)
print(a - c)
print(a * c)
print(a / c)

[1 2 3]
[4 5 6]
[-2 -1  0]
[3 6 9]
[0.33333333 0.66666667 1.        ]


In [ ]:
# vector norm
# euclidean norm (l2 norm)
print(np.linalg.norm(a))
print(np.sqrt(1**2 + 2**2 + 3**2))

# manhattan norm (L1 norm)
print(np.linalg.norm(a, ord=1))


3.7416573867739413
3.7416573867739413
6.0


# Matrix

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A.shape)

(2, 2)


In [ ]:
# element-wise operation

print(A + B)
print(A - B)
print(A * B)
print(A / B)

print('---')

# with scalar
c = 3
print(A + c)
print(A - c)
print(A * c)
print(A / c)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
---
[[4 5]
 [6 7]]
[[-2 -1]
 [ 0  1]]
[[ 3  6]
 [ 9 12]]
[[0.33333333 0.66666667]
 [1.         1.33333333]]


In [ ]:
# dot product
print(A)
print(B)
print(A @ B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [ ]:
# transpose

A= np.array([[1, 2, 3], [3, 4, 6]])
print(A)
print(A.T)

[[1 2 3]
 [3 4 6]]
[[1 3]
 [2 4]
 [3 6]]


## Matrix types

In [ ]:
# square matrix
A = np.array([[1,3], [3, 4]])

# identity matrix
I = np.eye(2)

print(A @ I)

[[1. 3.]
 [3. 4.]]


In [ ]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[-0.8  0.6]
 [ 0.6 -0.2]]


In [ ]:
A_inv @ A

array([[ 1.00000000e+00, -4.44089210e-16],
       [ 2.77555756e-17,  1.00000000e+00]])

# Array Manipulation, Aggregation, Indexing, Condition (masking)

In [ ]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

## Manipulation

In [ ]:
A.shape

(3, 4)

In [ ]:
A.ndim

2

In [ ]:
A.size

12

In [ ]:
# flatten (mengubah array nD menjadi 1D)
A.flatten().shape

(12,)

In [ ]:
# reshape
A.reshape(1,12)

array([[0.45053314, 0.17296777, 0.34376245, 0.5510652 , 0.54627315,
        0.05093587, 0.40067661, 0.55645993, 0.12697628, 0.82485143,
        0.26590556, 0.56917101]])

In [ ]:
# copy
B = A.copy()

## Indexing

In [ ]:
A

array([[0.45053314, 0.17296777, 0.34376245, 0.5510652 ],
       [0.54627315, 0.05093587, 0.40067661, 0.55645993],
       [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

## Aggregation

In [ ]:
A

array([[0.45053314, 0.17296777, 0.34376245, 0.5510652 ],
       [0.54627315, 0.05093587, 0.40067661, 0.55645993],
       [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [ ]:
print(A.max())
print(A.min(axis=0)[2])
print(A.sum(axis=1))

0.82485143
0.26590556
[1.51832856 1.55434556 1.78690428]


## Condition (masking)

In [ ]:
A

array([[0.45053314, 0.17296777, 0.34376245, 0.5510652 ],
       [0.54627315, 0.05093587, 0.40067661, 0.55645993],
       [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [ ]:
A<0.5

array([[ True,  True,  True, False],
       [False,  True,  True, False],
       [ True, False,  True, False]])

In [ ]:
A[A<0.5]

array([0.45053314, 0.17296777, 0.34376245, 0.05093587, 0.40067661,
       0.12697628, 0.26590556])

In [ ]:
A[[[ True,  True,  True, False],
       [False,  True,  True, False],
       [ True, False,  True, False]]]

array([0.45053314, 0.17296777, 0.34376245, 0.05093587, 0.40067661,
       0.12697628, 0.26590556])

# Studi kasus

In [ ]:
# dosen dengan 50 mhs

# nilai akhir = 0.2 tugas + 0.2 praktikum + 0.3 UTS + 0.3 UAS

nilai_tugas = np.random.normal(70, 10, 50)
nilai_praktikum = np.random.normal(80, 5, 50)
nilai_uts = np.random.normal(70, 5, 50)
nilai_uas = np.random.normal(75, 10, 50)
absen = np.arange(1,51)

In [ ]:
absen

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
nilai_akhir = 0.2 * nilai_tugas + 0.2 * nilai_praktikum + 0.3 * nilai_uts + 0.3 * nilai_uas
nilai_akhir

array([68.24651528, 69.02948917, 76.66856355, 70.93558794, 66.30755657,
       71.3646781 , 69.48724576, 66.53379398, 70.70165518, 67.61195255,
       69.53379987, 76.72785741, 77.22224981, 70.82901866, 71.17935465,
       75.54549071, 70.44604482, 64.19602482, 70.60587858, 74.16219451,
       76.0250289 , 68.76960627, 71.98811472, 75.2504082 , 70.96077651,
       65.70184609, 70.34553571, 77.63978614, 76.38086568, 72.55821742,
       68.26119791, 71.84891207, 72.38181883, 71.19970831, 76.74105586,
       75.12356547, 76.27316268, 73.14377968, 70.26216492, 72.6502416 ,
       65.72536606, 72.00606392, 74.45961601, 81.1581977 , 80.96616257,
       76.58001623, 71.05252762, 77.56834064, 71.28138233, 75.49730214])

In [ ]:
absen[~((nilai_uas < 70) & (nilai_akhir >70))]

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 16, 18, 20, 21,
       22, 24, 26, 28, 29, 30, 31, 34, 35, 36, 37, 38, 40, 41, 42, 43, 44,
       45, 46, 47, 48])

In [ ]:
# jumlah mahasiswa yang tidak lulus
nilai_akhir[nilai_akhir < 70].size

12

In [ ]:
absen[nilai_akhir < 70]

array([ 1,  2,  5,  7,  8, 10, 11, 18, 22, 26, 31, 41])

In [ ]:
nilai_akhir.mean()

72.34271440223654